spring:
    cloud:
        config:
            server:
                git:
                    uri: file:///Users/user/workspace/minlia/cloud/infrastructure/config-server/src/main/resources/config

server:
    port: 8888
