server:
    port: 8082




eureka:
    client:
    enabled: true
    serviceUrl:
      defaultZone: ${eureka.server.serviceUrl:http://localhost:8761/eureka/}


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG

